name: Codacy Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI and upload results
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          allow-network: true
          verbose: true
          # Important new flags:
          run-docker-tools: true
          gh-code-scanning-compat: true
